package com.vehiqon.common.enums;

public enum AuditAction {
    USER_PASSWORD_CHANGED,
    USER_VERIFIED_EMAIL,
    USER_REQUESTED_VERIFICATION_EMAIL_TOKEN,
    USER_PASSWORD_RESET_REQUESTED,
    USER_PASSWORD_RESET_COMPLETED,
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_LOGGED_OUT_ALL,
    PASSWORD_RESET,TOKEN_REFRESHED,
    EMAIL_VERIFIED,
    USER_REFRESHED_TOKEN
}
