package com.vehiqon.common.enums;

public enum EntityEnum {
    NONE,
    USER,
    VEHICLE,
    VEHICLE_DOCUMENT,
    SUBSCRIPTION_PLAN,
    USER_SUBSCRIPTION,
    USER_PERSONALISATION,
    CAR_DOCUMENTS,
    MAINTENANCE_REMINDER,
    MAINTENANCE,
    NOTIFICATIONS,
    NOMBA_TOKENS,
    PASSWORD_RESET_TOKEN,
    PAYMENTS,
    REFRESH_TOKEN,
    SERVICE_HISTORY,
    USER_ROLE,
    VERIFICATION_TOKEN,
    VIRTUAL_ACCOUNT

}
