spring.application.name=car-mgmt

server.port = 8085

#spring.datasource.url=${MYSQL_URL}
#spring.datasource.username=${MYSQL_USER}
#spring.datasource.password=${MYSQL_PASS}

#spring.datasource.driver-class-name=com.sql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# PostgreSQL Database Configuration
spring.datasource.url=${POSTGRES_LOCAL_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/cas-bank?sslmode=disable
#spring.datasource.url=jdbc:postgresql://db.jplthcpnsypjhbhlxddk.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_LOCAL_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Show SQL in the console
spring.jpa.show-sql=true
# Pretty-print SQL
spring.jpa.properties.hibernate.format_sql=true

# Optional: Show SQL parameter values
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#SSL Properties
#server.ssl.key-store=classpath:ssl/serverkeystore.jks
#server.ssl.key-store-type=JKS
#server.ssl.key-store-password=${SSL_STORE_PASS}
#server.ssl.key-alias=tcserver


spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}

# Protocol and Security Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# Optional Timeout Configurations (Prevents thread blocking)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

