
#logging.level.org.hibernate.stat=DEBUG
# Verbose logging and local PostgreSQL DB
logging.level.com.casdore=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/car-mgmt?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=password

# Show SQL queries in dev
spring.jpa.show-sql=true

# Optional: Show SQL parameter values
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#debug=true
#logging.level.org.flywaydb=DEBUG
#logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG


#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true