spring.application.name=vehiqon
spring.config.import=optional:file:.env[.properties]
server.port = 8085

# PostgreSQL Database Configuration
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.dependencies.depends-on=flyaway
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Show SQL in the console
#spring.jpa.show-sql=true
## Pretty-print SQL
#spring.jpa.properties.hibernate.format_sql=true

# Optional: Show SQL parameter values
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#SSL Properties
#server.ssl.key-store=classpath:ssl/serverkeystore.jks
#server.ssl.key-store-type=JKS
#server.ssl.key-store-password=${SSL_STORE_PASS}
#server.ssl.key-alias=tcserver


spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}

# Protocol and Security Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# Optional Timeout Configurations (Prevents thread blocking)
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.jackson.date-format=dd-MM-yyyy

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.web.access=TRACE
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

nomba.base-url= https://sandbox.nomba.com
nomba.client-id=${NOMBA_CLIENT_ID}
nomba.client-secret=${NOMBA_PRIVATE_KEY}
nomba.account-id=${NOMBA_ACCOUNT_ID}
nomba.sub-account-id: ${NOMBA_SUB_ACCOUNT_ID}
nomba.webhook-signing-key=${NOMBA_WEBHOOK_KEY}

springdoc.swagger-ui.persist-authorization=true

#debug=true
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

rate-limit.login.capacity=5
rate-limit.login.duration=1m

rate-limit.verify-email.capacity=5
rate-limit.verify-email.duration=1m

rate-limit.resend-verification-email.capacity=5
rate-limit.resend-verification-email.duration=1m

rate-limit.reset-password.capacity=10
rate-limit.reset-password.duration=1m

rate-limit.register.capacity=3
rate-limit.register.duration=1m

rate-limit.forgot-password.capacity=5
rate-limit.forgot-password.duration=15m

rate-limit.refresh-token.capacity=30
rate-limit.refresh-token.duration=1m

#metrics and health
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
appender=com.p6spy.engine.spy.appender.FileLogger
logfile=logs/p6spy.log
append=true
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)