spring.application.name=vehiqon
spring.config.import=optional:file:.env[.properties]

server.port = 8085

# PostgreSQL Database Configuration
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL in the console
#spring.jpa.show-sql=true
## Pretty-print SQL
#spring.jpa.properties.hibernate.format_sql=true

# Optional: Show SQL parameter values
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#SSL Properties
#server.ssl.key-store=classpath:ssl/serverkeystore.jks
#server.ssl.key-store-type=JKS
#server.ssl.key-store-password=${SSL_STORE_PASS}
#server.ssl.key-alias=tcserver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}

# Protocol and Security Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# Optional Timeout Configurations (Prevents thread blocking)
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.web.access=TRACE