package com.vehiqon.features.insights.analytics.enums;

import com.vehiqon.common.enums.EntityEnum;
import lombok.Getter;

public enum EventType {
//    USER_REGISTERED,
    LOGIN(FeatureEnum.AUTH, EntityEnum.USER),
    LOGOUT(FeatureEnum.AUTH, EntityEnum.USER),
    PASSWORD_CHANGED(FeatureEnum.AUTH, EntityEnum.USER),
    PROFILE_UPDATED(FeatureEnum.USER, EntityEnum.USER),
    ROLE_UPDATED(FeatureEnum.USER, EntityEnum.USER),
    ROLE_SYNCED(FeatureEnum.USER, EntityEnum.USER),
    USER_DELETED(FeatureEnum.USER, EntityEnum.USER),
    USER_RESTORED(FeatureEnum.USER, EntityEnum.USER),


    VEHICLE_CREATED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_DOCUMENT_UPLOADED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_DOCUMENT_UPDATED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_DOCUMENT_DELETED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_DOCUMENT_RESTORED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_VIEWED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_UPDATED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    GET_VEHICLE_STATISTICS(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_DELETED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_RESTORED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VIEW_VEHICLE_DOCUMENT(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    VEHICLE_SHARED(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),
    SEARCHED_CAR(FeatureEnum.VEHICLE, EntityEnum.VEHICLE),

    REMINDER_CREATED(FeatureEnum.MAINTENANCE_REMINDER, EntityEnum.MAINTENANCE_REMINDER),
    REMINDER_COMPLETED(FeatureEnum.MAINTENANCE_REMINDER, EntityEnum.MAINTENANCE_REMINDER),
    REMINDER_CANCELLED(FeatureEnum.MAINTENANCE_REMINDER, EntityEnum.MAINTENANCE_REMINDER),

    MAINTENANCE_VIEWED(FeatureEnum.MAINTENANCE, EntityEnum.MAINTENANCE),
    MAINTENANCE_CREATED(FeatureEnum.MAINTENANCE, EntityEnum.MAINTENANCE),
    MAINTENANCE_UPDATED(FeatureEnum.MAINTENANCE, EntityEnum.MAINTENANCE),
    MAINTENANCE_DELETED(FeatureEnum.MAINTENANCE, EntityEnum.MAINTENANCE),
    MAINTENANCE_COMPLETED(FeatureEnum.MAINTENANCE, EntityEnum.MAINTENANCE),

    PAYMENT_INITIATED(FeatureEnum.PAYMENTS, EntityEnum.PAYMENTS),
    PAYMENT_SUCCESS(FeatureEnum.PAYMENTS, EntityEnum.PAYMENTS),
    PAYMENT_FAILED(FeatureEnum.PAYMENTS, EntityEnum.PAYMENTS),

    SUBSCRIPTION_PURCHASED(FeatureEnum.SUBSCRIPTIONS, EntityEnum.USER_SUBSCRIPTION),
    SUBSCRIPTION_UPGRADED(FeatureEnum.SUBSCRIPTIONS,  EntityEnum.USER_SUBSCRIPTION),
    SUBSCRIPTION_RENEWED(FeatureEnum.SUBSCRIPTIONS, EntityEnum.USER_SUBSCRIPTION),

    DASHBOARD_OPENED(FeatureEnum.DASHBOARD, EntityEnum.USER_PERSONALISATION),
    WIDGET_CLICKED(FeatureEnum.DASHBOARD, EntityEnum.USER_PERSONALISATION),
    QUICK_ACTION_CLICKED(FeatureEnum.DASHBOARD, EntityEnum.USER_PERSONALISATION),

    NOTIFICATION_OPENED(FeatureEnum.NOTIFICATIONS, EntityEnum.NOTIFICATIONS),
    NOTIFICATION_DISMISSED(FeatureEnum.NOTIFICATIONS, EntityEnum.NOTIFICATIONS),
    NOTIFICATION_ACTION_CLICKED(FeatureEnum.NOTIFICATIONS,EntityEnum.NOTIFICATIONS);

//    WALLER_CREDITED(FeatureEnum.WALLET, EntityEnum.VIRTUAL_ACCOUNT),
//    WALLER_DEBITED(FeatureEnum.WALLET, EntityEnum.VIRTUAL_ACCOUNT),
//    WALLER_TRANSFER(FeatureEnum.WALLET, EntityEnum.VIRTUAL_ACCOUNT),
//    WALLER_REFUNDED(FeatureEnum.WALLET, EntityEnum.VIRTUAL_ACCOUNT);
//    SEARCH,
//    FILTER,
//    SORT

    @Getter
    private final FeatureEnum feature;
    @Getter
    private final EntityEnum entity;

    EventType(FeatureEnum feature, EntityEnum entity) {
        this.feature = feature;
        this.entity = entity;
    }
}
