package com.vehiqon.features.insights.analytics.enums;

public enum EventType {
    USER_REGISTERED,
    LOGIN,
    LOGOUT,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,

    CAR_CREATED,
    CAR_UPDATED,
    CAR_DELETED,
    CAR_VIEWED,
    CAR_SHARED,

    REMINDER_CREATED,
    REMINDER_COMPLETED,
    REMINDER_CANCELLED,
    SERVICE_BOOKED,
    SERVICE_COMPLETED,

    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_RENEWED,

    DASHBOARD_OPENED,
    WIDGET_CLICKED,
    QUICK_ACTION_CLICKED,

    NOTIFICATION_OPENED,
    NOTIFICATION_DISMISSED,
    NOTIFICATION_ACTION_CLICKED,

    SEARCH,
    FILTER,
    SORT
}
